start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 15

default-root-container-layout = 'accordion'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[workspace-to-monitor-force-assignment]
    Files = 'secondary'
    Browse = 'secondary'
    Dev = 'main'
    Tools = 'secondary'

[mode.main.binding]
    alt-space = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-ctrl-1 = 'workspace Files'
    alt-ctrl-2 = 'workspace Browse'
    alt-ctrl-3 = 'workspace Dev'
    alt-ctrl-4 = 'workspace Tools'

    alt-shift-1 = 'move-node-to-workspace Files'
    alt-shift-2 = 'move-node-to-workspace Browse'
    alt-shift-3 = 'move-node-to-workspace Dev'
    alt-shift-4 = 'move-node-to-workspace Tools'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-f = 'fullscreen'
    alt-ctrl-f = 'macos-native-fullscreen'

    alt-enter = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']